name: 'Publish Immutable Action Version'

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read

    steps:
      - name: CargoWall
        uses: code-cargo/cargowall-action@v1.0.2
      - name: Checking out
        uses: actions/checkout@v6
      - name: Publish
        id: publish
        uses: actions/publish-immutable-action@0.0.3
